### ISSUE TITLE
Search bash history

### ISSUE THREAD

**Issue by jjlorenzo** [bradleybossard/dotfiles#1]
I like your approach of a separate histfile, but I would like to know how do you usually reuse your previous input commands from the history?
Thanks

**Comment by bradleybossard** [comment]
@jjlorenzo To be honest, I don't use if much, I guess it's just there in case you need it.

For instance, I can `cd ~/.history; grep -irn search_term` and find all the bash commands I issued.

I think at one point in time I had ideas for being able to determine most used commands, statistics, etc.

**Comment by jjlorenzo** [comment]
Thanks, I suppose that but thanks for the confirmation.
